# Generated by Django 4.1.2 on 2022-10-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_callendar_collection_invoice_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['completed']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
    ]
